blank_issues_enabled: false
contact_links:
    - name: Questions (zppy-interfaces)
      url: https://github.com/E3SM-Project/zppy-interfaces/discussions/categories/questions
      about: |
          Ask questions and discuss with other zppy-interfaces community members here. Please
          browse the zppy-interfaces Discussions Forum or zppy-interfaces documentation first before asking a
          question to make sure it is not already answered. If you can't find an
          answer, please include a self-contained reproducible example with your
          question if possible. Thanks!
