# Conda development environment for testing local source code changes to zppy-interfaces before merging them to production (main branch).
# To set up:
# conda clean --all --y
# conda env create -f conda/dev.yml -n env_name
# pre-commit run --all-files
# pip install .
name: zppy-interfaces-dev
channels:
  - conda-forge
dependencies:
  # Build
  # =======================
  - python >=3.11,<3.14
  - pip
  - setuptools >= 60
  # Base
  # =================
  - beautifulsoup4
  - lxml
  - matplotlib-base >=3.8.2,<3.10
  - mpas_tools >=0.21.0
  - netcdf4
  - numpy >=2.0,< 2.1.0
  - output_viewer=1.3.3
  - pcmdi_metrics
  - xarray >=2023.02.0
  - xcdat >=0.7.3,<1.0
  # Testing
  # =======================
  - pytest
  - pytest-cov
  # Documentation
  # =======================
  - sphinx
  - sphinx-multiversion
  - sphinx_rtd_theme
  # Quality Assurance Tools
  # =======================
  # Run `pre-commit autoupdate` to get the latest pinned versions of 'rev' in
  # `.pre-commit.config.yaml`, then update the pinned versions here.
  - black ==25.1.0
  - flake8 ==7.3.0
  - isort ==6.0.1
  - mypy ==1.18.2
  - pre-commit ==4.3.0
  - types-PyYAML >=6.0.0
  # Developer Tools
  # =======================
  - tbump=6.9.0
  - ipykernel
